### ISSUE TITLE
Pet feed type filtering not working correctly

### ISSUE THREAD

**Issue by cvuorinen** [probaton/habotica#14]
Currently I am not able to feed any of my standard pets with standard food. When I select a standard pet from the dropdown, then the type dropdown changes so it only shows magic potion types. And same if I first choose standard type, then pet dropdown only shows quest pets.

Don't know if it's related, but I have already got all pets and mounts once and released them with the kennel keys.

**Comment by probaton** [comment]
Thanks for the report! Believe it or not that's actually not a use case I've ever tested as I'm too much of a wuss to buy a kennel key. I'd been laboring under the assumption that standard pets were coded the same way as others, but apparently that was naive. 

That leaves us with two options, depending on how tech-savvy you are. Either you have to wait for me build a test mode for Habotica so that I can easily reproduce your scenario, or you send me a copy of your userData.json. 

I've been meaning to build a test mode for a while now, as that solves a number of other problems I've been having, so it's not that I mind doing that, but I'm afraid that would take a while. 

With your userData.json it should probably be a really easy fix, but without some basic background in REST APIs I understand that might be a tall order. Please note that, if you do manage to get your hands on your userData.json file, I only need the `pets` section. I heartily encourage you do delete everything else for obvious privacy reasons.

**Comment by cvuorinen** [comment]
Thanks for looking into the issue. I'll take a closer look at my userData tomorrow and post here (currently on mobile).

**Comment by cvuorinen** [comment]
Here's an excerpt from the userdata.json (most of the standard ones have value of 5 so no need to list them all).

```json
"pets": {
            "Wolf-Base": 5,
            "TigerCub-Base": 5,
            "FlyingPig-RoyalPurple": 10,
            "Cactus-Desert": 5,
            "FlyingPig-Base": 5,
            "Wolf-RoyalPurple": 15,
            "PandaCub-Base": 5,
            "BearCub-Desert": 5,
            "Jackalope-RoyalPurple": 5,
            "PandaCub-Aquatic": -1,
            "PandaCub-Desert": 5,
            "BearCub-Golden": 5,
            "Cactus-RoyalPurple": 10,
            "TigerCub-Zombie": 5,
            "Wolf-White": 5,
            "TigerCub-Desert": 5,
            "LionCub-CottonCandyBlue": 5,
            ...
}
```

**Comment by cvuorinen** [comment]
Seems like that info alone cannot be used to determine which pets can be fed, as for example I have fed all bear cubs to mounts, but no other type of standard pets, but all of them still have value 5.

I guess you need to also look at the `mounts` section from userdata.

Here's my for example:
```json
"mounts": {
            "PandaCub-Base": null,
            "Orca-Base": true,
            "Wolf-Base": null,
            "Gryphon-RoyalPurple": true,
            "PandaCub-Glass": true,
            "Cactus-Desert": null,
            "BearCub-Golden": true,
            "Fox-Shade": null,
            "LionCub-CottonCandyBlue": null,
            "PandaCub-Aquatic": true,
            "TigerCub-Zombie": null,
            ...
}
```

**Comment by probaton** [comment]
Good catch! And thanks for saving me the trouble of having to ask you to pass on your mount data after realizing I was bug hunting in the wrong spot. 

Habotica actually already does use mount data to determine which pets can be fed, but blindly assumes that either a mount exists or it doesn't. I didn't take into account that the key to the kennels will leave the entry but change the value. D'oh. 

It's an easy fix though, now that we've pinpointed the problem. Google-Play-willing, you shouldn't have to wait more than a day or so for an update. 

Unless you want to fix it yourself of course ;)

**Comment by probaton** [comment]
Fix has been released and should trickle it's way down to your phone in the next few hours. Please double-check that everything is working as it should. Without having reset my pets myself the fix is based on theory rather than empirically testing.

**Comment by cvuorinen** [comment]
Can't see the update yet...
But I'll test it when it gets here. Thanks.

**Comment by cvuorinen** [comment]
Still no update for me. Are you sure it went through ok? (it shows last update May 15)

**Comment by probaton** [comment]
Release was bounced by Google. Fixed it, so it should be rolled out soon. Thanks for keeping your eye on the ball!

**Comment by cvuorinen** [comment]
Ok, now I got the update and it's working as expected. I can feed the pets until they grow to mounts. Thanks.
